### ISSUE TITLE
add pagestate matcher for embedded window mode calender

### ISSUE THREAD

**Issue by benmardana** [nuclearpidgeon/UoM-Timetable-to-iCal#17]
New myUnimelb student portal sometimes shows student portal in embedded page which doesn't trigger page action.

See screenshot: https://prnt.sc/jg3hje

Update required to activate extension and ensure functionality is maintained

**Comment by nuclearpidgeon** [comment]
Hey @shrimpheavennow , thanks for reporting this issue.

I've noticed in the past that usually when loading the timetable via the portal, it's loaded in an iframe that then gets 'popped' out a moment after loading, to become the full window of the currently open tab (which I didn't even know was possible...). Are you saying that you've particularly noticed that sometimes this pop-out never happens and it stays inside that embedded iframe?

If this is the case and you are able to reproduce it, would you mind supplying the following?

1. Full URL of the **portal** page that has the embedded iframe page in it
1. Screenshot of the DOM tree from your browser's developer tools on that page, leading down to the iframe that embeds the actual timetable. If the extension is going to be able to work on the top-level portal page, the extension will need to be able to find that iframe with some kind of selector or pattern match, then grab the root DOM node of that inner iframe and run the subject selection code on that instead of the normal page context. The DOM tree would be helpful in identifying a good way to pattern match.
